# NeuTTS Studio — Donations
# Support development with crypto

github: https://github.com/fardin-sabid

donation: [
  'bitcoin:bc1qxjckk0y0g2ucr5vslqe2v50g4ev2n9fq94tjre',
  'ethereum:0x6432029cd32b99021289d9fbaecd4a9cf5d9a660',
  'solana:CPar1hFc7ScYDki4ggKbHctuTdNR2ktNrdDWgqhJqgMR',
  'dogecoin:DQSvZQbumjduEa6oXrxUyXo8GEG4WibAHB'
]